"""Remainder verification and refinement for flowpipe construction."""
from typing import List, Callable, Tuple, Optional
import math

from TERA.TMCore.TMVector import TMVector
from TERA.TMCore.Interval import Interval
from TERA.TMCore.TaylorModel import TaylorModel
from TERA.TMCore.Polynomial import Polynomial
from TERA.TMFlow import Picard

def compute_initial_guess(current_tmv: TMVector, remainder_estimation: List[Interval], state_dim: Optional[int] = None) -> TMVector:
    """Create an initial remainder guess for Picard verification."""

    if state_dim is None:
        if len(remainder_estimation) != len(current_tmv):
            raise ValueError("Remainder estimation dimension does not match TMVector dimension.")
    else:
        if not (0 < state_dim <= len(current_tmv)):
            raise ValueError("state_dim must be in (0, len(current_tmv)].")
        if len(remainder_estimation) != state_dim:
            raise ValueError("Remainder estimation dimension does not match state_dim.")
        
    # Create a copy to avoid mutating the original polynomial flowpipe
    guess_tmv = current_tmv.copy()
    
    assign_dim = len(guess_tmv) if state_dim is None else state_dim
    for i in range(assign_dim):
        # Assign the user-provided guess
        guess_tmv.tms[i].remainder = remainder_estimation[i]
        
    return guess_tmv


def verify_remainder(guess_tmv: TMVector, x0: TMVector,ode_rhs: Callable[[TMVector], TMVector], time_var: str,
    time_step: Interval, time_start: float, order: int, cutoff_threshold: float,
    state_dim: Optional[int] = None,
    precomputed_truncation_errors: Optional[List[Interval]] = None):
    """Verify that the guessed remainder encloses Picard propagation."""

    # apply picard operator with interval arithmetic
    tmv_tmp = Picard.compute_verified_step(
        x_poly=guess_tmv,
        x0=x0,
        ode_rhs=ode_rhs,
        time_var=time_var,
        time_step=time_step,
        order=order,
        cutoff_threshold=cutoff_threshold,
        time_start=time_start
    )

    if tmv_tmp is None:
        # picard evaluation failed (e.g., division by interval containing 0)
        return False, None, []

    # compute polynomial difference (truncation error)
    # truncation error relies only on polynomial of tmv_tmp and guess_tmv 
    # (these don't change per step) -> reused to avoid redundant calls
    check_dim = len(tmv_tmp) if state_dim is None else state_dim
    if precomputed_truncation_errors is not None:
        truncation_errors = precomputed_truncation_errors
    else:
        truncation_errors = []
        for i in range(check_dim):
            # calculate P_out - P_in
            poly_diff = tmv_tmp.tms[i].poly - guess_tmv.tms[i].poly
            
            # bound difference over domain
            # captures floating point noise + high order terms generated by f(P)
            eval_domain = guess_tmv.tms[i].domain
            diff_bound = poly_diff.range_evaluate(eval_domain)

            trunc_rad = diff_bound.radius()
            truncation_errors.append(Interval(-trunc_rad, trunc_rad))

    # add uncertainties onto remainder to get total error
    for i in range(check_dim):
        tmv_tmp.tms[i].remainder += truncation_errors[i]

    # perform inclusion check to ensure computed_error <= guessed_error
    success = True
    for i in range(check_dim):
        computed_rem = tmv_tmp.tms[i].remainder
        guess_rem = guess_tmv.tms[i].remainder
            
        # strict subset check: computed range must be inside guess range
        if not guess_rem.encloses(computed_rem):
            success = False
            break
                
    return success, tmv_tmp, truncation_errors

def refine_remainder(verified_tmv: TMVector, x0: TMVector, ode_rhs: Callable[[TMVector], TMVector], time_var: str,
    time_step: Interval, order: int, truncation_errors: List[Interval], jacobian,
    max_refinements: int = 40, stop_ratio: float = 0.99) -> TMVector:
    """Refine a verified remainder using a Jacobian-based update."""
    current_tmv = verified_tmv
    dimension = len(current_tmv.tms)
    current_rems = [tm.remainder for tm in current_tmv.tms]

    h = float(time_step.upper)
    EPS_ABS = 1e-11
    EPS_REL = 1e-6

    for k in range(max_refinements):
        old_max = max(r.width() for r in current_rems)
        # compute next_rems radii = trunc_rad + h*(|J|*cur_rads)
        cur_rads = [iv.radius() for iv in current_rems]
        next_rems = []
        for r in range(dimension):
            trunc_rad = truncation_errors[r].radius()
            acc = 0.0
            for c in range(dimension):
                Jij = jacobian[r][c]
                max_abs = max(abs(float(Jij.lower)), abs(float(Jij.upper)))
                acc += max_abs * float(cur_rads[c])

            rad_next = float(trunc_rad) + h * acc
            rad_next = max(0.0, rad_next)
            next_rems.append(Interval(-rad_next, rad_next))

        new_max = max(r.width() for r in next_rems)

        # abort if numerically insane
        if not math.isfinite(float(new_max)) or float(new_max) > 1e30:
            # print(f"[DBG][refine][ABORT] iter={k} new_max_width={new_max}")
            break

        # accept tiny numerical jitter near the noise floor.
        expanded = False
        for i in range(dimension):
            old_w = float(current_rems[i].width())
            new_w = float(next_rems[i].width())

            if old_w < EPS_ABS and new_w < EPS_ABS:
                continue

            if new_w > old_w * (1.0 + EPS_REL):
                expanded = True
                break
        if expanded:
            # if any component expands, stop refining and keep the last safe remainders
            break

        # if improvement is tiny, accept one last tightening and stop
        if new_max >= old_max * stop_ratio:
            if new_max < old_max:
                current_rems = next_rems
            break

        # otherwise accept and continue
        current_rems = next_rems

    for i in range(dimension):
        current_tmv.tms[i].remainder = current_rems[i]
    return current_tmv
